rapidapi:
  name:
    endpoint: https://restcountries-v1.p.rapidapi.com/name
  alpha:
    endpoint: https://restcountries-v1.p.rapidapi.com/alpha/
  key: c97952862fmshe72152dc748a296p1e92b3jsn1351a36f4b6a
exchange:
  api:
    validate: https://api.exchangeratesapi.io/latest

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 883485912187-jmi3cjg59p4batg1f4j7583n0m4j0j28.apps.googleusercontent.com
            clientSecret: wxledSq6wDzzhtHehK-Btwue

logging:
  level:
    org.springframework.security: DEBUG